##### Commonly used ggplot additions ####

#### Functions to generate ggplot annotations ####
calculate_median <- function(x, round_to = 4){
  #' calculate_median
  #'
  #' A function to annotate the graph with the median value of the observations.
  #' @param x a vector of numeric values
  #' @param round_to the number of decimal places to which the median needs to be rounded. Default is 4.
  #' @keywords median, summary statistics, graph annotations
  #' @export
  #' @examples
  #' x <- runif(n = 100, min = 2, max = 200)
  #' calculate_median(x)
  #' @return A y coordinate and the median of the values in the vector supplied to the function. The median is rounded
  #' to four decimal places by default, but this can be changed in the arguments. For example:
  #'    y    label
  #' 67.5568 n = 100
  #' These annotations are inserted into the graph object generated by ggplot at the coordinates specified under "y"
  #' once this function is run as specified under usage
  #' @usage
  #' p <- p + stat_summary(fun.data = calculate_median, geom = "text")
  #'
  #' data.frame() retains the median value as numeric.
  #' However, c() makes both y and label a character since paste0 produces an output of type character.
  return(data.frame(y = median(x)*(1.2), label = sprintf("%0.4f", median(x))))
}

calculate_n <- function(x){
  #' calculate_median
  #'
  #' A function to annotate the graph with the number of samples
  #' @param x a vector of numeric values
  #' @keywords sample size, graph annotations
  #' @export
  #' @examples
  #' x <- runif(n = 100, min = 2, max = 200)
  #' calculate_n(x)
  #' @return A y coordinate and the number of the values in the vector supplied to the function. The result is expressed
  #' as a string "n = numeric value`. For example:
  #'    y    label
  #' 67.5568 n = 100
  #' These annotations are inserted into the graph object generated by ggplot at the coordinates specified under "y"
  #' once this function is run as specified under usage
  #' @usage
  #' p <- p + stat_summary(fun.data = calculate_n, geom = "text")
  #'
  #' data.frame() retains the median value as numeric.
  #' However, c() makes both y and label a character since paste0 produces an output of type character.
  return(data.frame(y = median(x)*(0.8), label = paste0("n = ",length(x))))
}
